In [23]:
!pip show pandas

Name: pandas
Version: 2.2.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: C:\Users\hp\miniconda3\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: seaborn

pandas for analysis
- dataset
  - dictionary of items
  - list of dictionary
  - csv file
  - excel file
  - json file
  - sql connection
- creating dataframe
- reading data
- selection of data
- manipulating data
- cleaning data
- visualizing data

In [24]:
import pandas as pd

In [25]:
books = {
    'title': ['The art of war', 'The final empire', 'Harry Potter'],
    'author': ['Sun Tzu', 'Brandon Sanderson', 'J K Rowling'],
    'price': [399, 1099, 499]
}
pd.DataFrame(books)

              title             author  price
0    The art of war            Sun Tzu    399
1  The final empire  Brandon Sanderson   1099
2      Harry Potter        J K Rowling    499

In [26]:
movies = [
    {'title': "PK", 'director': "Rajkumar Hirani", 'year': "2014"},
    {'title': "I", 'director': "Shankar", 'year': "2015"},
    {'title': "Pink", 'director': "Aniruddha Roy Chowdhary", 'year': "2016"}
]
pd.DataFrame(movies)

  title                 director  year
0    PK          Rajkumar Hirani  2014
1     I                  Shankar  2015
2  Pink  Aniruddha Roy Chowdhary  2016

In [27]:
pd.read_csv('dummy.csv')

   id  product   price
0   1    apple     100
1   2   banana      50
2   3   orange      80

In [28]:
pd.read_json('dummy.json')

       name  age            email
0  John Doe   25  jonny@gmail.com
1  Jane Doe   24   jane@gmail.com

In [29]:
pd.read_excel(r"C:\Users\hp\OneDrive\ドキュメント\Dummy.xlsx")

   #      name   college
0  1     Krish     Amity
1  2   Avichal     Amity
2  3  Shantanu       ITI
3  4  Himanshu  Kuchbhiu

In [30]:
url = 'https://raw.githubusercontent.com/digipodium/Datasets/main/regression/kc_house_data.csv'
df = pd.read_csv(url)
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

first steps after reading the data
- `df.head(nrows)` - first n rows
- `df.tail(nrows)` - last n rows
- `df.sample(nrows)` - random n rows
- `df.info()` - data types, missing values
- `df.describe()` - summary statistics
- `df.shape` - number of rows and columns
- `df.columns` - column names

In [31]:
df.head(2)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639

In [32]:
df.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [33]:
df.sample(3)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
10646,2725069157,20140613T000000,883000.0,4,2.50,3670,54450,2.0,0,0,...,10,3670,0,1999,0,98074,47.6211,-122.016,2900,49658
14079,5702380770,20150428T000000,280000.0,4,2.25,1600,7916,2.0,0,0,...,7,1600,0,1991,0,98022,47.1940,-121.981,1540,7242
18172,6083000123,20150504T000000,158000.0,3,1.00,1140,10477,1.0,0,0,...,6,1140,0,1942,0,98168,47.4874,-122.306,1190,9750

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [35]:
df.describe() # summary statistics for numerical columns (default)

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [36]:
df.describe(include='object') # summary statistics for object columns

                   date
count             21613
unique              372
top     20140623T000000
freq                142

In [37]:
df.shape

(21613, 21)

In [38]:
print(df.columns.tolist())

['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15']

In [39]:
# simple sort
df.sort_values('bedrooms')

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3119,3918400017,20150205T000000,380000.0,0,0.00,1470,979,3.0,0,2,...,8,1470,0,2006,0,98133,47.7145,-122.356,1470,1399
3467,1453602309,20140805T000000,288000.0,0,1.50,1430,1650,3.0,0,0,...,7,1430,0,1999,0,98125,47.7222,-122.290,1430,1650
6994,2954400190,20140624T000000,1295650.0,0,0.00,4810,28008,2.0,0,0,...,12,4810,0,1990,0,98053,47.6642,-122.069,4740,35061
4868,6896300380,20141002T000000,228000.0,0,1.00,390,5900,1.0,0,0,...,4,390,0,1953,0,98118,47.5260,-122.261,2170,6000
9773,3374500520,20150429T000000,355000.0,0,0.00,2460,8049,2.0,0,0,...,8,2460,0,1990,0,98031,47.4095,-122.168,2520,8050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19254,8812401450,20141229T000000,660000.0,10,3.00,2920,3745,2.0,0,0,...,7,1860,1060,1913,0,98105,47.6635,-122.320,1810,3745
13314,627300145,20140814T000000,1148000.0,10,5.25,4590,10920,1.0,0,2,...,9,2500,2090,2008,0,98004,47.5861,-122.113,2730,10400
15161,5566100170,20141029T000000,650000.0,10,2.00,3610,11914,2.0,0,0,...,7,3010,600,1958,0,98006,47.5705,-122.175,2040,11914
8757,1773100755,20140821T000000,520000.0,11,3.00,3000,4960,2.0,0,0,...,7,2400,600,1918,1999,98106,47.5560,-122.363,1420,4960
15870,2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,...,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700

# Selecting data in pandas
- dataframe
  - rows
    - iloc - index based location
    - iloc - label based location
  - columns
    - single column selection
    - multiple column selection
    - column selection by data type
  - conditional selection
    - boolean indexing
    - query method

In [40]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [41]:
# select rows from iloc
df.iloc[100] # index 100th row

id                    1952200240
date             20140611T000000
price                   850830.0
bedrooms                       3
bathrooms                    2.5
sqft_living                 2070
sqft_lot                   13241
floors                       1.5
waterfront                     0
view                           0
condition                      5
grade                          9
sqft_above                  1270
sqft_basement                800
yr_built                    1910
yr_renovated                   0
zipcode                    98102
lat                      47.6415
long                    -122.315
sqft_living15               2200
sqft_lot15                  4500
Name: 100, dtype: object

In [42]:
# random 5 rows
df.iloc[[1,59,100,200,300]] # index [1,59,100,200,300] rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
59,8079040320,20150223T000000,430000.0,4,3.00,1850,9976,2.0,0,0,...,8,1850,0,1991,0,98059,47.5059,-122.149,2270,8542
100,1952200240,20140611T000000,850830.0,3,2.50,2070,13241,1.5,0,0,...,9,1270,800,1910,0,98102,47.6415,-122.315,2200,4500
200,3542300060,20150311T000000,210000.0,3,1.00,860,11725,1.0,0,0,...,6,860,0,1943,0,98056,47.5093,-122.184,1300,9514
300,3225069065,20140624T000000,3075000.0,4,5.00,4550,18641,1.0,1,4,...,10,2600,1950,2002,0,98074,47.6053,-122.077,4550,19508

In [43]:
# random 5 rows, with selected columns
df.iloc[[1,10,20], [0,11,12,3,4]]

            id  grade  sqft_above  bedrooms  bathrooms
1   6414100192      7        2170         3       2.25
10  1736800520      8        1860         3       2.50
20  6300500875      7         860         4       1.75

In [44]:
df.iloc[15:50, :10] # index 15-49 rows, 0-9 columns (slicing)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view
15,9297300055,20150124T000000,650000.0,4,3.00,2950,5000,2.0,0,3
16,1875500060,20140731T000000,395000.0,3,2.00,1890,14040,2.0,0,0
17,6865200140,20140529T000000,485000.0,4,1.00,1600,4300,1.5,0,0
18,16000397,20141205T000000,189000.0,2,1.00,1200,9850,1.0,0,0
19,7983200060,20150424T000000,230000.0,3,1.00,1250,9774,1.0,0,0
20,6300500875,20140514T000000,385000.0,4,1.75,1620,4980,1.0,0,0
21,2524049179,20140826T000000,2000000.0,3,2.75,3050,44867,1.0,0,4
22,7137970340,20140703T000000,285000.0,5,2.50,2270,6300,2.0,0,0
23,8091400200,20140516T000000,252700.0,2,1.50,1070,9643,1.0,0,0
24,3814700200,20141120T000000,329000.0,3,2.25,2450,6500,2.0,0,0
25,1202000200,20141103T000000,233000.0,3,2.00,1710,4697,1.5,0,0
26,1794500383,20140626T000000,937000.0,3,1.75,2450,2691,2.0,0,0
27,3303700376,20141201T000000,667000.0,3,1.00,1400,1581,1.5,0,0
28,5101402488,20140624T000000,438000.0,3,1.75,1520,6380,1.0,0,0
29,1873100390,20150302T000000,719000.0,4,2.50,2570,7173,2.0,0,0
30,8562750320,20141110T000000,580500.0,3,2.50,2320,3980,2.0,0,0
31,2426039314,20141201T000000,280000.0,2,1.50,1190,1265,3.0,0,0
32,461000390,20140624T000000,687500.0,4,1.75,2330,5000,1.5,0,0
33,7589200193,20141110T000000,535000.0,3,1.00,1090,3000,1.5,0,0
34,7955080270,20141203T000000,322500.0,4,2.75,2060,6659,1.0,0,0
35,9547205180,20140613T000000,696000.0,3,2.50,2300,3060,1.5,0,0
36,9435300030,20140528T000000,550000.0,4,1.00,1660,34848,1.0,0,0
37,2768000400,20141230T000000,640000.0,4,2.00,2360,6000,2.0,0,0
38,7895500070,20150213T000000,240000.0,4,1.00,1220,8075,1.0,0,0
39,2078500320,20140620T000000,605000.0,4,2.50,2620,7553,2.0,0,0
40,5547700270,20140715T000000,625000.0,4,2.50,2570,5520,2.0,0,0
41,7766200013,20140811T000000,775000.0,4,2.25,4220,24186,1.0,0,0
42,7203220400,20140707T000000,861990.0,5,2.75,3595,5639,2.0,0,0
43,9270200160,20141028T000000,685000.0,3,1.00,1570,2280,2.0,0,0
44,1432701230,20140729T000000,309000.0,3,1.00,1280,9656,1.0,0,0
45,8035350320,20140718T000000,488000.0,3,2.50,3160,13603,2.0,0,0
46,8945200830,20150325T000000,210490.0,3,1.00,990,8528,1.0,0,0
47,4178300310,20140716T000000,785000.0,4,2.50,2290,13416,2.0,0,0
48,9215400105,20150428T000000,450000.0,3,1.75,1250,5963,1.0,0,0
49,822039084,20150311T000000,1350000.0,3,2.50,2753,65005,1.0,1,2

In [45]:
# selecting columns based on indexes
df.iloc[:, [0,5,10,11]]

               id  sqft_living  condition  grade
0      7129300520         1180          3      7
1      6414100192         2570          3      7
2      5631500400          770          3      6
3      2487200875         1960          5      7
4      1954400510         1680          3      8
...           ...          ...        ...    ...
21608   263000018         1530          3      8
21609  6600060120         2310          3      8
21610  1523300141         1020          3      7
21611   291310100         1600          3      8
21612  1523300157         1020          3      7

[21613 rows x 4 columns]

In [46]:
# updating index column
df = df.set_index('id')
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

loc is used when index is set

In [47]:
df.loc[[1954400510, 7129300520]]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
1954400510,20150218T000000,510000.0,3,2.0,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7129300520,20141013T000000,221900.0,3,1.0,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650

### Column Selection
- dictionary like selection
  - `dataframe['column_name']`
- object like selection
  - `dataframe.column_name`
### Multiple Column Selection
- dictionary like selection
  - `dataframe[list_of_column_names]`

In [48]:
df['price']

id
7129300520    221900.0
6414100192    538000.0
5631500400    180000.0
2487200875    604000.0
1954400510    510000.0
                ...
263000018     360000.0
6600060120    400000.0
1523300141    402101.0
291310100     400000.0
1523300157    325000.0
Name: price, Length: 21613, dtype: float64

In [49]:
df.bedrooms

id
7129300520    3
6414100192    3
5631500400    2
2487200875    4
1954400510    3
             ..
263000018     3
6600060120    4
1523300141    2
291310100     3
1523300157    2
Name: bedrooms, Length: 21613, dtype: int64

In [50]:
df[['bedrooms', 'price', 'sqft_living']]

            bedrooms     price  sqft_living
id
7129300520         3  221900.0         1180
6414100192         3  538000.0         2570
5631500400         2  180000.0          770
2487200875         4  604000.0         1960
1954400510         3  510000.0         1680
...              ...       ...          ...
263000018          3  360000.0         1530
6600060120         4  400000.0         2310
1523300141         2  402101.0         1020
291310100          3  400000.0         1600
1523300157         2  325000.0         1020

[21613 rows x 3 columns]

In [51]:
col_list = ['grade', 'condition', 'yr_built']
df[col_list]

            grade  condition  yr_built
id
7129300520      7          3      1955
6414100192      7          3      1951
5631500400      6          3      1933
2487200875      7          5      1965
1954400510      8          3      1987
...           ...        ...       ...
263000018       8          3      2009
6600060120      8          3      2014
1523300141      7          3      2009
291310100       8          3      2004
1523300157      7          3      2008

[21613 rows x 3 columns]

## Boolean Indexing
`df['column'] > value`

`df['column'] == value`

`df['column'] != value`

In [52]:
df[df['price'] > 300000]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [53]:
df[df['condition'] >= 5]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1202000200,20141103T000000,233000.0,3,2.00,1710,4697,1.5,0,0,5,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
3303700376,20141201T000000,667000.0,3,1.00,1400,1581,1.5,0,0,5,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
822039084,20150311T000000,1350000.0,3,2.50,2753,65005,1.0,1,2,5,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
5072410070,20141021T000000,505000.0,3,1.75,2519,8690,2.0,0,0,5,8,2519,0,1973,0,98166,47.4428,-122.344,2500,9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7518504130,20140626T000000,663000.0,3,2.00,1480,3876,1.0,0,0,5,7,860,620,1928,0,98117,47.6808,-122.382,1660,3774
3902100175,20140728T000000,850000.0,5,3.00,3900,5250,1.5,0,1,5,8,2620,1280,1931,0,98116,47.5577,-122.389,1950,5700
3449000060,20141001T000000,320000.0,3,1.00,1400,9000,1.0,0,0,5,7,1400,0,1959,0,98059,47.5022,-122.145,1440,8400
2888000030,20140926T000000,500000.0,4,2.25,2270,8196,1.0,0,0,5,7,1150,1120,1963,0,98034,47.7214,-122.227,1920,10122
522059130,20150429T000000,465000.0,3,1.00,1150,18200,1.0,0,0,5,7,1150,0,1959,0,98058,47.4262,-122.187,1714,18200

In [54]:
# 5 star rated house + 2 floors
df[(df['condition'] == 5) & (df['floors'] == 2)]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
5072410070,20141021T000000,505000.0,3,1.75,2519,8690,2.0,0,0,5,8,2519,0,1973,0,98166,47.4428,-122.344,2500,9500
2331300505,20140613T000000,822500.0,5,3.50,2320,4960,2.0,0,0,5,7,1720,600,1926,0,98103,47.6763,-122.352,1700,4960
3127200041,20140613T000000,589000.0,4,3.00,2440,9600,2.0,0,0,5,7,2440,0,1961,0,98034,47.7044,-122.200,2290,9600
7424700045,20150513T000000,2050000.0,5,3.00,3830,8480,2.0,0,1,5,9,2630,1200,1905,1994,98122,47.6166,-122.287,3050,7556
9297300045,20140709T000000,550000.0,3,2.00,1970,4166,2.0,0,3,5,8,1270,700,1929,0,98126,47.5717,-122.375,2390,4166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3528900330,20140707T000000,1450000.0,4,3.25,3770,4103,2.0,0,0,5,9,2710,1060,1925,0,98109,47.6410,-122.349,2560,4160
6822100155,20140512T000000,630000.0,4,2.00,1770,6000,2.0,0,0,5,7,1770,0,1911,1981,98199,47.6493,-122.401,1340,6000
3529300330,20141107T000000,370000.0,3,2.50,1980,6922,2.0,0,0,5,8,1980,0,1991,0,98031,47.3960,-122.184,2090,7697
4137020820,20141027T000000,268000.0,4,3.00,1840,7510,2.0,0,0,5,8,1840,0,1988,2013,98092,47.2595,-122.218,1650,7957
3271800910,20140701T000000,1356920.0,4,3.50,4270,5800,2.0,0,3,5,10,3170,1100,1937,0,98199,47.6474,-122.411,3100,5800

In [55]:
f1 = df['price'] > 100000
f2 = df['condition'] == 5
f3 = df['floors'] == 2
df[f1 & f2 & f3]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
5072410070,20141021T000000,505000.0,3,1.75,2519,8690,2.0,0,0,5,8,2519,0,1973,0,98166,47.4428,-122.344,2500,9500
2331300505,20140613T000000,822500.0,5,3.50,2320,4960,2.0,0,0,5,7,1720,600,1926,0,98103,47.6763,-122.352,1700,4960
3127200041,20140613T000000,589000.0,4,3.00,2440,9600,2.0,0,0,5,7,2440,0,1961,0,98034,47.7044,-122.200,2290,9600
7424700045,20150513T000000,2050000.0,5,3.00,3830,8480,2.0,0,1,5,9,2630,1200,1905,1994,98122,47.6166,-122.287,3050,7556
9297300045,20140709T000000,550000.0,3,2.00,1970,4166,2.0,0,3,5,8,1270,700,1929,0,98126,47.5717,-122.375,2390,4166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3528900330,20140707T000000,1450000.0,4,3.25,3770,4103,2.0,0,0,5,9,2710,1060,1925,0,98109,47.6410,-122.349,2560,4160
6822100155,20140512T000000,630000.0,4,2.00,1770,6000,2.0,0,0,5,7,1770,0,1911,1981,98199,47.6493,-122.401,1340,6000
3529300330,20141107T000000,370000.0,3,2.50,1980,6922,2.0,0,0,5,8,1980,0,1991,0,98031,47.3960,-122.184,2090,7697
4137020820,20141027T000000,268000.0,4,3.00,1840,7510,2.0,0,0,5,8,1840,0,1988,2013,98092,47.2595,-122.218,1650,7957
3271800910,20140701T000000,1356920.0,4,3.50,4270,5800,2.0,0,3,5,10,3170,1100,1937,0,98199,47.6474,-122.411,3100,5800

In [56]:
df[f1 & f2 & f3].reset_index().style.highlight_max(color='blue')

In [57]:
df[f1 & f2 & f3].reset_index().style.background_gradient(cmap='cool')

In [58]:
df[f1 & f2 & f3].reset_index().style.set_properties(color='red', subset=['price'])

In [59]:
# query
df.query('price > 250000')

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [60]:
df.query('price > 2500000 & condition == 5')

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
9471200370,20150330T000000,2537000.0,4,3.00,3710,20000,2.0,0,2,5,10,2760,950,1936,0,98105,47.6696,-122.261,3970,20000
6065300840,20150501T000000,2850000.0,4,4.00,5040,17208,1.0,0,0,5,10,2870,2170,1976,0,98006,47.5701,-122.188,4050,18647
4217402115,20150421T000000,3650000.0,6,4.75,5480,19401,1.5,1,4,5,11,3910,1570,1936,0,98105,47.6515,-122.277,3510,15810
7159200005,20140507T000000,3200000.0,7,4.50,6210,8856,2.5,0,2,5,11,4760,1450,1910,0,98109,47.6307,-122.354,2940,5400
9185700485,20150401T000000,2538000.0,4,3.50,4350,6000,2.0,0,0,5,10,2970,1380,1908,0,98112,47.6277,-122.286,4190,7200
3761100045,20140618T000000,3000000.0,4,4.25,4850,12445,2.0,1,4,5,10,3850,1000,1989,0,98034,47.7011,-122.244,3350,12210
1069000070,20150415T000000,2795000.0,5,3.25,4590,12793,2.0,0,2,5,11,3590,1000,1928,0,98199,47.6453,-122.410,2920,8609
1954700410,20140801T000000,2546000.0,4,3.00,4190,8805,2.5,0,2,5,9,3490,700,1928,0,98112,47.6181,-122.284,3780,8558
1732800780,20150212T000000,3065000.0,5,3.00,4150,7500,2.5,0,4,5,11,3510,640,1909,0,98119,47.6303,-122.362,2250,4050
5317100750,20140711T000000,2920000.0,4,4.75,4575,24085,2.5,0,2,5,10,3905,670,1926,0,98112,47.6263,-122.284,3900,9687
1346300150,20141020T000000,3300000.0,8,4.00,7710,11750,3.5,0,0,5,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
6613000930,20140902T000000,2950000.0,4,3.25,3890,25470,2.0,1,3,5,10,3030,860,1923,0,98105,47.6608,-122.269,4140,19281

In [61]:
df.query('price > 2500000 & condition == 5').sort_values('price')

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
9471200370,20150330T000000,2537000.0,4,3.00,3710,20000,2.0,0,2,5,10,2760,950,1936,0,98105,47.6696,-122.261,3970,20000
9185700485,20150401T000000,2538000.0,4,3.50,4350,6000,2.0,0,0,5,10,2970,1380,1908,0,98112,47.6277,-122.286,4190,7200
1954700410,20140801T000000,2546000.0,4,3.00,4190,8805,2.5,0,2,5,9,3490,700,1928,0,98112,47.6181,-122.284,3780,8558
1069000070,20150415T000000,2795000.0,5,3.25,4590,12793,2.0,0,2,5,11,3590,1000,1928,0,98199,47.6453,-122.410,2920,8609
6065300840,20150501T000000,2850000.0,4,4.00,5040,17208,1.0,0,0,5,10,2870,2170,1976,0,98006,47.5701,-122.188,4050,18647
5317100750,20140711T000000,2920000.0,4,4.75,4575,24085,2.5,0,2,5,10,3905,670,1926,0,98112,47.6263,-122.284,3900,9687
6613000930,20140902T000000,2950000.0,4,3.25,3890,25470,2.0,1,3,5,10,3030,860,1923,0,98105,47.6608,-122.269,4140,19281
3761100045,20140618T000000,3000000.0,4,4.25,4850,12445,2.0,1,4,5,10,3850,1000,1989,0,98034,47.7011,-122.244,3350,12210
1732800780,20150212T000000,3065000.0,5,3.00,4150,7500,2.5,0,4,5,11,3510,640,1909,0,98119,47.6303,-122.362,2250,4050
7159200005,20140507T000000,3200000.0,7,4.50,6210,8856,2.5,0,2,5,11,4760,1450,1910,0,98109,47.6307,-122.354,2940,5400
1346300150,20141020T000000,3300000.0,8,4.00,7710,11750,3.5,0,0,5,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
4217402115,20150421T000000,3650000.0,6,4.75,5480,19401,1.5,1,4,5,11,3910,1570,1936,0,98105,47.6515,-122.277,3510,15810

Manipulation of Data
 - removing columns and rows
 - renaming column
 - adding column
 - changing data type
 - handling missing value
 - droping missing value
 - using apply()method

In [62]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [63]:
cols_to_drop = ['sqft_living15', 'sqft_lot15']
df = df.drop(columns=cols_to_drop)

In [64]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'],
      dtype='object')

In [65]:
df.drop(labels=[9471200370, 9185700485, 1954700410])

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299

In [66]:
df.drop_duplicates(subset=['date']) # always use a subset column

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4047200825,20141011T000000,400000.0,1,1.00,1390,60984,1.0,0,0,3,6,1390,0,1960,0,98019,47.7652,-121.903
2064800880,20150201T000000,301500.0,3,1.00,1410,7419,1.0,0,0,3,7,1050,360,1969,0,98056,47.5340,-122.173
126059310,20141130T000000,1000000.0,3,2.25,3040,52302,1.0,0,0,3,9,3040,0,2005,0,98072,47.7635,-122.112
984220330,20140824T000000,325000.0,4,2.50,1820,9161,1.0,0,0,4,7,1220,600,1975,0,98058,47.4333,-122.168
2827100075,20140727T000000,286308.0,2,1.50,1220,1036,3.0,0,0,3,7,1220,0,2006,0,98133,47.7348,-122.347

In [67]:
df.dropna() # remove rows with any NaN Value

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299

In [68]:
# renaming columns
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'],
      dtype='object')

In [69]:
name_uodate = {
    'lat': 'latitude',
    'long': 'longitude'
}
df.rename(columns=name_uodate)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,latitude,longitude
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299

In [70]:
# dummy column add
df['dummy'] = "house_price" # repeats same value in all rows
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,dummy
id,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,house_price
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,house_price
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,house_price
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,house_price
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,house_price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,house_price
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,house_price
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,house_price
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,house_price
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,house_price

In [71]:
df['age'] = 2024 - df['yr_built'] # add a new column age
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,dummy,age
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,house_price,69
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,house_price,73
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,house_price,91
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,house_price,59
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,house_price,37

In [75]:
df = df.drop['dummy']

TypeError: 'method' object is not subscriptable

In [72]:
# rearranging columns - first copy the columns
print(df.columns.tolist())

['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'dummy', 'age']

In [74]:
# paste the list and rearranging columns as per your choice
columns_seq = ['dummy', 'date', 'bedrooms', 'bathrooms', 'floors', 'waterfront', 'view', 'sqft_living', 'sqft_lot',
             'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'age', 'condition',  'grade', 'zipcode', 'lat', 'long', 'price']
df = df[columns_seq].copy() # copy the rearranged columns to df
df.head()

,dummy,date,bedrooms,bathrooms,floors,waterfront,view,sqft_living,sqft_lot,sqft_above,sqft_basement,yr_built,yr_renovated,age,condition,grade,zipcode,lat,long,price
id,,,,,,,,,,,,,,,,,,,,
7129300520,house_price,20141013T000000,3,1.00,1.0,0,0,1180,5650,1180,0,1955,0,69,3,7,98178,47.5112,-122.257,221900.0
6414100192,house_price,20141209T000000,3,2.25,2.0,0,0,2570,7242,2170,400,1951,1991,73,3,7,98125,47.7210,-122.319,538000.0
5631500400,house_price,20150225T000000,2,1.00,1.0,0,0,770,10000,770,0,1933,0,91,3,6,98028,47.7379,-122.233,180000.0
2487200875,house_price,20141209T000000,4,3.00,1.0,0,0,1960,5000,1050,910,1965,0,59,5,7,98136,47.5208,-122.393,604000.0
1954400510,house_price,20150218T000000,3,2.00,1.0,0,0,1680,8080,1680,0,1987,0,37,3,8,98074,47.6168,-122.045,510000.0

In [76]:
df.floors.dtype

dtype('float64')

In [77]:
df.floors.astype('int') # convert to int

id
7129300520    1
6414100192    2
5631500400    1
2487200875    1
1954400510    1
             ..
263000018     3
6600060120    2
1523300141    2
291310100     2
1523300157    2
Name: floors, Length: 21613, dtype: int64

In [78]:
df.floors = df.floors.astype('int')
df.head()

,dummy,date,bedrooms,bathrooms,floors,waterfront,view,sqft_living,sqft_lot,sqft_above,sqft_basement,yr_built,yr_renovated,age,condition,grade,zipcode,lat,long,price
id,,,,,,,,,,,,,,,,,,,,
7129300520,house_price,20141013T000000,3,1.00,1,0,0,1180,5650,1180,0,1955,0,69,3,7,98178,47.5112,-122.257,221900.0
6414100192,house_price,20141209T000000,3,2.25,2,0,0,2570,7242,2170,400,1951,1991,73,3,7,98125,47.7210,-122.319,538000.0
5631500400,house_price,20150225T000000,2,1.00,1,0,0,770,10000,770,0,1933,0,91,3,6,98028,47.7379,-122.233,180000.0
2487200875,house_price,20141209T000000,4,3.00,1,0,0,1960,5000,1050,910,1965,0,59,5,7,98136,47.5208,-122.393,604000.0
1954400510,house_price,20150218T000000,3,2.00,1,0,0,1680,8080,1680,0,1987,0,37,3,8,98074,47.6168,-122.045,510000.0

In [80]:
import numpy as np

In [82]:
fake_df = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[6,7,np.nan,9,10],
    'C':[11,12,13,14,None],
    'D':[16,17,np.nan,20,np.nan]
})
fake_df

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0  17.0
2  3   NaN  13.0   NaN
3  4   9.0  14.0  20.0
4  5  10.0   NaN   NaN

In [83]:
fake_df.dropna() # should not be done - rookie mistake

   A    B     C     D
0  1  6.0  11.0  16.0
1  2  7.0  12.0  17.0
3  4  9.0  14.0  20.0

In [86]:
df.isnull().sum()

dummy            0
date             0
bedrooms         0
bathrooms        0
floors           0
waterfront       0
view             0
sqft_living      0
sqft_lot         0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
age              0
condition        0
grade            0
zipcode          0
lat              0
long             0
price            0
dtype: int64

In [87]:
fake_df.isnull().sum()

A    0
B    1
C    1
D    2
dtype: int64

In [88]:
fake_df

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0  17.0
2  3   NaN  13.0   NaN
3  4   9.0  14.0  20.0
4  5  10.0   NaN   NaN

In [89]:
fake_df.fillna(0)

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0  17.0
2  3   0.0  13.0   0.0
3  4   9.0  14.0  20.0
4  5  10.0   0.0   0.0

In [90]:
fake_df['B'].mean()

np.float64(8.0)

In [91]:
b_mean = fake_df['B'].mean()
fake_df.B = fake_df.B.replace(np.nan, b_mean)
fake_df

   A     B     C     D
0  1   6.0  11.0  16.0
1  2   7.0  12.0  17.0
2  3   8.0  13.0   NaN
3  4   9.0  14.0  20.0
4  5  10.0   NaN   NaN

In [92]:
fake_df.D = fake_df.D.fillna(fake_df.D.mean()) # fill the mean
fake_df

   A     B     C          D
0  1   6.0  11.0  16.000000
1  2   7.0  12.0  17.000000
2  3   8.0  13.0  17.666667
3  4   9.0  14.0  20.000000
4  5  10.0   NaN  17.666667